package com.carmangment.app.core

import com.carmangment.app.core.finance.LoanCalculator
import com.carmangment.app.core.holidays.IranHolidays
import com.carmangment.app.core.jalali.Jalali
import com.carmangment.app.core.rates.IncomeCalculator
import com.carmangment.app.core.rates.Rates
import com.carmangment.app.core.rates.ServiceType
import com.carmangment.app.core.rates.TimeRates
import kotlinx.serialization.json.*
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Behavioural parity gate between the retired React Native implementation and this
 * native core.
 *
 * `golden.json` was generated by EXECUTING the original JS modules
 * (utils/jalali.ts, utils/timeRates.ts, utils/iranHolidays.ts and the income /
 * loan logic from contexts/AppContext.tsx). Every number in it is what the shipped
 * app actually produced, so any behavioural drift in the port fails the build.
 *
 * The one deliberate divergence is the Jalali calendar, whose vectors were
 * regenerated with the corrected algorithm. See [Jalali] for the two defects that
 * were fixed and why; [jalaliMatchesOfficialAnchors] and
 * [jalaliRoundTripsEveryDayFor100Years] independently prove the new behaviour is
 * the correct one rather than merely different.
 */
class GoldenParityTest {

    private val golden: JsonObject by lazy {
        val stream = javaClass.classLoader!!.getResourceAsStream("golden.json")
            ?: error("golden.json missing from test resources")
        Json.parseToJsonElement(stream.bufferedReader().readText()).jsonObject
    }

    private fun JsonObject.arr(key: String) = this[key]!!.jsonArray
    private fun JsonElement.str(k: String) = jsonObject[k]!!.jsonPrimitive.content
    private fun JsonElement.strOrNull(k: String) =
        jsonObject[k]?.takeIf { it !is JsonNull }?.jsonPrimitive?.content
    private fun JsonElement.int(k: String) = jsonObject[k]!!.jsonPrimitive.int
    private fun JsonElement.dbl(k: String) = jsonObject[k]!!.jsonPrimitive.double

    private val eps = 1e-9

    // ---------------------------------------------------------------- calendar

    @Test
    fun jalaliMatchesOfficialAnchors() {
        // Documented Nowruz dates + a leap-year Esfand 30. These are the ground truth
        // that the old gregorianToJalali failed on.
        val anchors = listOf(
            Triple(1390, 1, 1) to Triple(2011, 3, 21),
            Triple(1391, 1, 1) to Triple(2012, 3, 20),
            Triple(1392, 1, 1) to Triple(2013, 3, 21),
            Triple(1395, 1, 1) to Triple(2016, 3, 20),
            Triple(1396, 1, 1) to Triple(2017, 3, 21),
            Triple(1399, 1, 1) to Triple(2020, 3, 20),
            Triple(1400, 1, 1) to Triple(2021, 3, 21),
            Triple(1402, 1, 1) to Triple(2023, 3, 21),
            Triple(1403, 1, 1) to Triple(2024, 3, 20),
            Triple(1404, 1, 1) to Triple(2025, 3, 21),
            Triple(1405, 1, 1) to Triple(2026, 3, 21),
            Triple(1403, 12, 30) to Triple(2025, 3, 20),
            Triple(1404, 6, 1) to Triple(2025, 8, 23),
        )
        for ((j, g) in anchors) {
            assertEquals("j->g $j", g, Jalali.toGregorian(j.first, j.second, j.third))
            val back = Jalali.fromGregorian(g.first, g.second, g.third)
            assertEquals("g->j $g", j, Triple(back.year, back.month, back.day))
        }
    }

    @Test
    fun leapYearsMatchOfficialList() {
        val official = setOf(1391, 1395, 1399, 1403, 1408, 1412, 1416, 1420, 1424, 1428)
        for (y in 1390..1430) {
            assertEquals("leap($y)", official.contains(y), Jalali.isLeapYear(y))
        }
    }

    @Test
    fun jalaliRoundTripsEveryDayFor100Years() {
        var checked = 0
        for (y in 1350..1450) {
            for (m in 1..12) {
                for (d in 1..Jalali.monthLength(y, m)) {
                    val (gy, gm, gd) = Jalali.toGregorian(y, m, d)
                    val back = Jalali.fromGregorian(gy, gm, gd)
                    assertEquals("round-trip ${Jalali.format(y, m, d)}",
                        Triple(y, m, d), Triple(back.year, back.month, back.day))
                    checked++
                }
            }
        }
        assertEquals("expected 36,890 days across 1350-1450", 36890, checked)
    }

    @Test
    fun monthLengthsMatchGolden() {
        for (v in golden.arr("monthLen")) {
            val y = v.int("y"); val m = v.int("m")
            assertEquals("monthLength($y,$m)", v.int("len"), Jalali.monthLength(y, m))
        }
    }

    @Test
    fun dayOfWeekMatchesGolden() {
        for (v in golden.arr("dowVectors")) {
            val d = v.str("j")
            assertEquals("dayOfWeek($d)", v.int("dow"), Jalali.dayOfWeek(d))
        }
    }

    @Test
    fun addMonthsMatchesGolden() {
        for (v in golden.arr("addMonthVectors")) {
            val base = v.str("base"); val n = v.int("n")
            assertEquals("addMonths($base,$n)", v.str("out"), Jalali.addMonths(base, n))
        }
    }

    @Test
    fun addMonthsNeverProducesInvalidDate() {
        // The JS version emitted "1404/12/30", which does not exist.
        for (y in 1395..1425) {
            for (m in 1..12) {
                for (day in listOf(1, 29, 30, 31)) {
                    if (day > Jalali.monthLength(y, m)) continue
                    val base = Jalali.format(y, m, day)
                    for (n in -24..24) {
                        val out = Jalali.addMonths(base, n)
                        val p = Jalali.parse(out)!!
                        assertTrue("addMonths($base,$n) produced invalid $out",
                            Jalali.isValid(p.year, p.month, p.day))
                    }
                }
            }
        }
    }

    @Test
    fun weekRangesMatchGolden() {
        for (v in golden.arr("weekVectors")) {
            val d = v.str("j")
            val (start, end) = Jalali.weekRange(d)
            assertEquals("weekStart($d)", v.str("start"), start)
            assertEquals("weekEnd($d)", v.str("end"), end)
        }
    }

    // ------------------------------------------------------------------ time

    private fun boundariesNamed(name: String): TimeRates.Boundaries = when (name) {
        "default" -> TimeRates.DEFAULT_BOUNDARIES
        "custom_1900_2200_0500" -> TimeRates.Boundaries(19 * 60, 22 * 60, 5 * 60)
        "custom_1600_1800_0730" -> TimeRates.Boundaries(16 * 60, 18 * 60, 7 * 60 + 30)
        else -> error("unknown boundary set $name")
    }

    @Test
    fun durationSplitMatchesGolden() {
        val vectors = golden.arr("splitVectors")
        assertTrue("expected the full split matrix", vectors.size >= 500)
        for (v in vectors) {
            val b = boundariesNamed(v.str("boundaries"))
            val s = v.str("start"); val e = v.str("end")
            val got = TimeRates.splitDuration(s, e, b)
            val tag = "${v.str("boundaries")} $s->$e"
            assertEquals("normal $tag", v.dbl("normal"), got.normal, eps)
            assertEquals("night $tag", v.dbl("night"), got.night, eps)
            assertEquals("sahar $tag", v.dbl("sahar"), got.sahar, eps)
        }
    }

    @Test
    fun startBracketPercentMatchesGolden() {
        for (v in golden.arr("bracketVectors")) {
            val s = v.str("start")
            assertEquals("bracket($s)", v.dbl("percent"),
                TimeRates.startBracketPercent(s, 10.0, 20.0), eps)
        }
    }

    @Test
    fun hourlyBreakdownMatchesGolden() {
        for (v in golden.arr("hourlyVectors")) {
            val hours = v.dbl("hours")
            val s = v.strOrNull("start"); val e = v.strOrNull("end")
            val got = TimeRates.computeHourlyBreakdown(
                hours, s, e, v.dbl("rate"), v.dbl("nightPercent"), v.dbl("saharPercent"),
            )
            val tag = "h=$hours $s->$e n=${v.dbl("nightPercent")} s=${v.dbl("saharPercent")}"
            assertEquals("normalHours $tag", v.dbl("normalHours"), got.normalHours, 1e-8)
            assertEquals("nightHours $tag", v.dbl("nightHours"), got.nightHours, 1e-8)
            assertEquals("saharHours $tag", v.dbl("saharHours"), got.saharHours, 1e-8)
            assertEquals("totalAmount $tag", v.dbl("totalAmount"), got.totalAmount, 1e-4)
        }
    }

    // ---------------------------------------------------------------- income

    @Test
    fun serviceIncomeMatchesGolden() {
        val vectors = golden.arr("incomeVectors")
        assertTrue("expected the full income matrix", vectors.size >= 200)
        for (v in vectors) {
            val type = ServiceType.fromWire(v.str("type"))
            val start = v.str("startTime").ifEmpty { null }
            val end = v.str("endTime").ifEmpty { null }
            val got = IncomeCalculator.calculate(
                serviceType = type,
                km = v.dbl("km"),
                hours = v.dbl("hours"),
                tollCount = v.int("tollCount"),
                missionFood = v.dbl("missionFood"),
                missionToll = v.dbl("missionToll"),
                missionFine = v.dbl("missionFine"),
                rates = Rates.DEFAULT,
                startTime = start,
                endTime = end,
            )
            assertEquals(
                "income ${v.str("type")} km=${v.dbl("km")} h=${v.dbl("hours")} $start->$end toll=${v.int("tollCount")}",
                v.int("income").toLong(), got,
            )
        }
    }

    @Test
    fun availableServiceHasNoKmComponent() {
        val r = Rates.DEFAULT
        val income = IncomeCalculator.calculate(
            ServiceType.AVAILABLE, km = 500.0, hours = 0.0, tollCount = 0,
            missionFood = 0.0, missionToll = 0.0, missionFine = 0.0, rates = r,
        )
        assertEquals(0L, income)
    }

    // ----------------------------------------------------------------- loans

    @Test
    fun loanSchedulesMatchGolden() {
        for (v in golden.arr("loanVectors")) {
            val loan = v.jsonObject["loan"]!!.jsonObject
            val date = loan["date"]!!.jsonPrimitive.content
            val total = loan["totalAmount"]!!.jsonPrimitive.double
            val interest = loan["interestPercent"]!!.jsonPrimitive.double
            val count = loan["installmentsCount"]!!.jsonPrimitive.int
            val paid = loan["paidInstallments"]!!.jsonArray.map { it.jsonPrimitive.int }

            assertEquals("total $date", v.int("total").toLong(),
                LoanCalculator.totalWithInterest(total, interest))

            val expected = v.jsonObject["schedule"]!!.jsonArray
            val got = LoanCalculator.schedule(date, total, interest, count, paid)
            assertEquals("schedule size $date", expected.size, got.size)
            for (i in got.indices) {
                val exp = expected[i]
                assertEquals("index", exp.int("index"), got[i].index)
                assertEquals("amount #${got[i].index} $date",
                    exp.int("amount").toLong(), got[i].amount)
                assertEquals("paid #${got[i].index} $date",
                    exp.jsonObject["paid"]!!.jsonPrimitive.boolean, got[i].paid)
            }
            // Schedule must always sum exactly to the total with interest.
            assertEquals("sum $date", v.int("total").toLong(), got.sumOf { it.amount })
        }
    }

    @Test
    fun loanScheduleDueDatesAreAlwaysValid() {
        val got = LoanCalculator.schedule("1404/06/31", 100_000_000.0, 18.0, 60, emptyList())
        for (inst in got) {
            val p = Jalali.parse(inst.dueDate)!!
            assertTrue("invalid due date ${inst.dueDate}", Jalali.isValid(p.year, p.month, p.day))
        }
    }

    @Test
    fun malformedLoanYieldsEmptySchedule() {
        assertTrue(LoanCalculator.schedule(null, 1.0, 1.0, 3, emptyList()).isEmpty())
        assertTrue(LoanCalculator.schedule("garbage", 1.0, 1.0, 3, emptyList()).isEmpty())
        assertTrue(LoanCalculator.schedule("14/6/1", 1.0, 1.0, 3, emptyList()).isEmpty())
    }

    // -------------------------------------------------------------- holidays

    @Test
    fun officialHolidaysMatchGolden() {
        val byYear = golden["holidayVectors"]!!.jsonObject
        for ((yearKey, list) in byYear) {
            val year = yearKey.toInt()
            val expected = list.jsonArray
            val got = IranHolidays.forYear(year)
            assertEquals("holiday count $year", expected.size, got.size)
            for (i in got.indices) {
                assertEquals("holiday date $year #$i", expected[i].str("date"), got[i].date)
                assertEquals("holiday title $year #$i", expected[i].str("title"), got[i].title)
            }
        }
    }

    @Test
    fun holidayTitleResolvesFirstMatch() {
        // 1404/01/02 exists in both the solar and lunar tables; solar must win,
        // exactly as the JS `find()` did.
        assertEquals("عید نوروز", IranHolidays.titleFor("1404/01/02"))
        assertTrue(IranHolidays.isOfficialHoliday("1404/01/01"))
        assertTrue(IranHolidays.isOfficialHoliday("1404/11/22"))
    }

    @Test
    fun yearsWithoutLunarDataStillReturnSolarHolidays() {
        val got = IranHolidays.forYear(1410)
        assertEquals(10, got.size)
        assertTrue(got.all { it.date.startsWith("1410/") })
    }
}
